package aula06;

/**
 *
 * @author lucianoo_gp
 */
public class Tela1 extends javax.swing.JFrame {

    /**
     * Creates new form Tela1
     */
    public Tela1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumero1 = new javax.swing.JTextField();
        txtNumero2 = new javax.swing.JTextField();
        btnSomar = new javax.swing.JButton();
        txtResultado = new javax.swing.JTextField();
        btnSubtrair = new javax.swing.JToggleButton();
        btnDividir = new javax.swing.JToggleButton();
        btnMultiplicar = new javax.swing.JToggleButton();
        cmbOperacoes = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("TlwgTypewriter", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        txtNumero1.setBackground(new java.awt.Color(204, 204, 204));
        txtNumero1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero1.setAlignmentY(0.0F);
        txtNumero1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 48, 160, 24));

        txtNumero2.setBackground(new java.awt.Color(204, 204, 204));
        txtNumero2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero2.setAlignmentY(0.0F);
        txtNumero2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 90, 160, 24));

        btnSomar.setBackground(new java.awt.Color(255, 51, 51));
        btnSomar.setText("+");
        btnSomar.setAlignmentY(0.0F);
        btnSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSomar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 132, 32, -1));

        txtResultado.setBackground(new java.awt.Color(204, 204, 204));
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultado.setAlignmentY(0.0F);
        txtResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 213, 160, 24));

        btnSubtrair.setBackground(new java.awt.Color(255, 51, 51));
        btnSubtrair.setText("-");
        btnSubtrair.setAlignmentY(0.0F);
        btnSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtrairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubtrair, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 132, 32, -1));

        btnDividir.setBackground(new java.awt.Color(255, 51, 51));
        btnDividir.setText("/");
        btnDividir.setAlignmentY(0.0F);
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });
        getContentPane().add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 132, 32, -1));

        btnMultiplicar.setBackground(new java.awt.Color(255, 51, 51));
        btnMultiplicar.setText("*");
        btnMultiplicar.setAlignmentY(0.0F);
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 132, 34, -1));

        cmbOperacoes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "/", "*" }));
        getContentPane().add(cmbOperacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 174, -1, -1));

        btnCalcular.setText("=");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 174, 68, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero1ActionPerformed

    }//GEN-LAST:event_txtNumero1ActionPerformed

    private void txtNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero2ActionPerformed

    }//GEN-LAST:event_txtNumero2ActionPerformed

    private void btnSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomarActionPerformed
        calcular('+');
    }//GEN-LAST:event_btnSomarActionPerformed

    private void btnSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtrairActionPerformed
        calcular('-');
    }//GEN-LAST:event_btnSubtrairActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        calcular('/');
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        calcular('*');
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        String op = cmbOperacoes.getSelectedItem().toString();
        
        calcular(op.charAt(0));
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void calcular(char op) {
        String strResultado;
        switch (op) {
            case '+' -> {
                strResultado = String.valueOf(Double.parseDouble(txtNumero1.getText()) + Double.parseDouble(txtNumero2.getText()));
                txtResultado.setText(strResultado);
                break;
            }
            case '-' -> {
                strResultado = String.valueOf(Double.parseDouble(txtNumero1.getText()) - Double.parseDouble(txtNumero2.getText()));
                txtResultado.setText(strResultado);
                break;
            }
            case '/' -> {
                strResultado = String.valueOf(Double.parseDouble(txtNumero1.getText()) / Double.parseDouble(txtNumero2.getText()));
                txtResultado.setText(strResultado);
                break;
            }
            case '*' -> {
                strResultado = String.valueOf(Double.parseDouble(txtNumero1.getText()) * Double.parseDouble(txtNumero2.getText()));
                txtResultado.setText(strResultado);
                break;
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCalcular;
    private javax.swing.JToggleButton btnDividir;
    private javax.swing.JToggleButton btnMultiplicar;
    private javax.swing.JButton btnSomar;
    private javax.swing.JToggleButton btnSubtrair;
    private javax.swing.JComboBox<String> cmbOperacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
