Algoritmo "area_retangulo"
Var
base,altura,area:real
Inicio
//entrada de dados
escreval ("==========================================")
escreval ("Qual o tamanho da base do retângulo?")
leia (base)
escreval
escreval ("Qual a altura do retângulo?")
leia (altura)
escreval
// processamento de dados
area<-(base*altura)
//saída de dados
escreval ("A área do retângulo é:",area)
escreval ("==========================================")
Fimalgoritmo