Algoritmo "calc_val_final"
Var
p1,p2,p3,p4,p5:caracter
q1,q2,q3,q4,q5:inteiro
v1,v2,v3,v4,v5,total:real
Inicio
escreval ("----------------------------------")
escreval ("Cálculo de cobrança para 5 produtos")
escreval
escreval ("Identifique o produto:")
leia (p1)
escreval ("Qual a quantidade?")
leia (q1)
escreval ("Qual o valor?:")
leia (v1)
escreval
escreval ("Identifique o produto:")
leia (p2)
escreval ("Qual a quantidade?")
leia (q2)
escreval ("Qual o valor?:")
leia (v2)
escreval
escreval ("Identifique o produto:")
leia (p3)
escreval ("Qual a quantidade?")
leia (q3)
escreval ("Qual o valor?:")
leia (v3)
escreval
escreval ("Identifique o produto:")
leia (p4)
escreval ("Qual a quantidade?")
leia (q4)
escreval ("Qual o valor?:")
leia (v4)
escreval
escreval ("Identifique o produto:")
leia (p5)
escreval ("Qual a quantidade?")
leia (q5)
escreval ("Qual o valor?:")
leia (v5)
escreval
escreval ("----------------------------------")
total <- ((q1*v1)+(q2*v2)+(q3*v3)+(q4*v4)+(q5*v5))
escreval
escreval ("O valor total é de: R$",total)
Fimalgoritmo